### ISSUE TITLE
not showing game

### ISSUE THREAD

**Issue by Manjunath-Bhat** [omgimanerd/game-framework#1]
localhost:5000 is blank, not displaying anything.
showing  error in the console like this:
DevTools failed load SourceMap

**Comment by omgimanerd** [comment]
This repository is slightly outdated, I have updated the template code and the accompany blog post. The console warning is expected. Please provide steps to reproduce for any future bug reports.

**Comment by Manjunath-Bhat** [comment]
Hi Alvin,
Thanks for the update.You are very kind.
I will look into it.
